# Use the official stellar-core image as the base image
FROM stellar/stellar-core:21.1.1-1923.b3aeb14cc.focal

# Install redis-cli
RUN apt-get update && apt-get install -y redis-tools dnsutils net-tools iputils-ping

# Set the default command to be overridden by the Kubernetes job
CMD ["sh", "-c", "echo 'This is a placeholder command'"]
