apiVersion: batch/v1
kind: Job
metadata:
  name: preload-redis
spec:
  template:
    spec:
      containers:
      - name: preload
        image: redis:latest
        command: ["/bin/sh", "-c"]
        args: 
        - |
          until redis-cli -h redis -p 6379 ping; do echo waiting for redis; sleep 2; done;
          apply=1000;
          for i in $(seq 0 100); do
            target=$(( (i + 1) * 10000 ));
            redis-cli -h redis -p 6379 LPUSH ranges "${target}/${apply}";
          done
      restartPolicy: OnFailure