apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-monitor
  template:
    metadata:
      labels:
        app: job-monitor
    spec:
      containers:
      - name: job-monitor
        image: your-docker-registry/job-monitor:latest
        ports:
        - containerPort: 5000
