---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        command: ["redis-server"]
        # We have disabled persistence below. There was some error with cross-device link. Will figure out later.
        # Storage mounting works fine
        # args: ["--appendonly", "yes"] # Enable persistence with AOF
        # volumeMounts:
        # - mountPath: /data
        #   name: redis-storage
      # volumes:
      # - name: redis-storage
      #   persistentVolumeClaim:
      #     claimName: redis-pvc
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: redis-pv
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: manual
#   hostPath:
#     path: /mnt/data
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: manual
#   resources:
#     requests:
#       storage: 1Gi
