apiVersion: v1
kind: Service
metadata:
  name: catchup-workers
spec:
  type: ClusterIP
  ports:
    - port: 11625
      targetPort: 11625
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stellar-core
  labels:
    app: stellar-core
spec:
  serviceName: "stellar-core"
  replicas: 3
  selector:
    matchLabels:
      app: stellar-core
  template:
    metadata:
      labels:
        app: stellar-core
    spec:
      containers:
      - name: stellar-core
        image: stellar/stellar-core:20.4.1-1851.60263deeb.focal
        command: ["/bin/sh", "-c"]
        args: 
        - |
          REDIS_HOST = "redis"
          REDIS_PORT=6379
          SLEEP_INTERVAL=5

          while true; do
            # Fetch the next job key from the Redis queue
            JOB_KEY=$(redis-cli -h $REDIS_HOST -p $REDIS_PORT LPOP job_queue)

            if [ -n "$JOB_KEY" ]; then
              echo "Processing job: $JOB_KEY"
              # Run the shell command with the job key
              /usr/bin/stellar-core --conf /config/stellar-core.cfg new-db;
              /usr/bin/stellar-core --conf /config/stellar-core.cfg catchup 10000/100 --metric ledger.transaction.apply;              
              # Check the exit status of the command
              if [ $? -ne 0 ]; then
                echo "Error processing job: $JOB_KEY"
              else
                echo "Successfully processed job: $JOB_KEY"
              fi
            else
              echo "No more jobs in the queue. Sleeping for $SLEEP_INTERVAL seconds..."
              sleep $SLEEP_INTERVAL
            fi
          done
        ports:
        - containerPort: 11625
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /config
      volumes:
      - name: data
        emptyDir:
          sizeLimit: "1Gi"
      - name: config
        configMap:
          name: stellar-core-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stellar-core-config
data:
  stellar-core.cfg: |
    HTTP_PORT=11625
    PUBLIC_HTTP_PORT=false
    NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
    DATABASE="sqlite3:///data/stellar.db"
    BUCKET_DIR_PATH="/data/buckets"
    LOG_FILE_PATH="/data/stellar-core-{datetime:%Y-%m-%d_%H-%M-%S}.log"    
    ENABLE_SOROBAN_DIAGNOSTIC_EVENTS=true
    DEPRECATED_SQL_LEDGER_STATE=false

    [[HOME_DOMAINS]]
    HOME_DOMAIN="testnet.stellar.org"
    QUALITY="HIGH"

    [[VALIDATORS]]
    NAME="sdftest1"
    HOME_DOMAIN="testnet.stellar.org"
    PUBLIC_KEY="GDKXE2OZMJIPOSLNA6N6F2BVCI3O777I2OOC4BV7VOYUEHYX7RTRYA7Y"
    ADDRESS="core-testnet1.stellar.org"
    HISTORY="curl -sf http://history.stellar.org/prd/core-testnet/core_testnet_001/{0} -o {1}"

    [[VALIDATORS]]
    NAME="sdftest2"
    HOME_DOMAIN="testnet.stellar.org"
    PUBLIC_KEY="GCUCJTIYXSOXKBSNFGNFWW5MUQ54HKRPGJUTQFJ5RQXZXNOLNXYDHRAP"
    ADDRESS="core-testnet2.stellar.org"
    HISTORY="curl -sf http://history.stellar.org/prd/core-testnet/core_testnet_002/{0} -o {1}"
    
    [[VALIDATORS]]
    NAME="sdftest3"
    HOME_DOMAIN="testnet.stellar.org"
    PUBLIC_KEY="GC2V2EFSXN6SQTWVYA5EPJPBWWIMSD2XQNKUOHGEKB535AQE2I6IXV2Z"
    ADDRESS="core-testnet3.stellar.org"
    HISTORY="curl -sf http://history.stellar.org/prd/core-testnet/core_testnet_003/{0} -o {1}"
