apiVersion: v1
kind: PersistentVolume
metadata:
  name: stellar-core-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/stellar-core

