apiVersion: batch/v1
kind: Job
metadata:
  name: preload-redis
spec:
  template:
    spec:
      containers:
      - name: preload
        image: redis:latest
        command: ["/bin/sh", "-c"]
        args: 
        - {{ .Values.job.args | nindent 10 }}
      initContainers:
      - name: wait-for-redis
        image: redis:latest
        command: ['sh', '-c', "until redis-cli -h {{ .Values.redis.host }} -p {{ .Values.redis.port }} ping; do echo waiting for redis; sleep 2; done;"]
      restartPolicy: OnFailure