redis:
  host: "redis"
  port: 6379
  job_queue: "ranges"
  success_queue: "succeeded"
  failed_queue: "failed"
  progress_queue: "in_progress"

worker:
  replicas: 5 # number of workers running in the StatefulSet

monitor:
  logging_interval_seconds: 10

job:
  args: |
    until redis-cli -h redis -p 6379 ping; do echo waiting for redis; sleep 2; done;
    latestLedgerNum=100000;
    ledgersPerJob=1600;
    overlapLedgers=0;
    startingLedger=0;
    endRange=$latestLedgerNum;
    while [ "$endRange" -gt "$startingLedger" ]; do
        ledgersToApply=$((ledgersPerJob + overlapLedgers));
        echo "${endRange}/${ledgersToApply}";
        redis-cli -h redis -p 6379 RPUSH ranges "${endRange}/${ledgersToApply}";
        endRange=$(( endRange - ledgersPerJob ));
    done
